<x-layouts.app>
    <x-slot name="title">Do‘kon xaritasi — AquaOptom</x-slot>
    <x-slot name="header">Qanday ishlaydi?</x-slot>
    <x-workspace-guide icon="🧭" title="Do‘koningiz, bitta oddiy xaritada" description="Nima qilmoqchisiz? Quyidagi kerakli bo‘limni tanlang. Mahsulot, pul va qarz o‘zgarishlari bir-biriga bog‘langan." />
    <div class="guide-grid">
        <a class="guide-tile" href="{{ route('inventory.inward') }}"><span>📥</span><h2>Mahsulot keldi</h2><p>Nom → litr → dona → kirim narxi → yetkazuvchi → to‘lov.</p><small>Mahsulot omborga qo‘shiladi. To‘lanmagan summa yetkazuvchiga qarz bo‘ladi.</small><b>Kirim qilish →</b></a>
        <a class="guide-tile" href="{{ route('sales.pos') }}"><span>⚡</span><h2>Tezda sotmoqchiman</h2><p>Mahsulot → dona → narx → to‘liq to‘lov.</p><small>Mijozsiz sotish mumkin. Donani yozing: 200 dona uchun 200 marta bosish kerak emas.</small><b>Tezkor sotuv →</b></a>
        <a class="guide-tile" href="{{ route('sales.pos', ['mode' => 'customer']) }}"><span>👤</span><h2>Mijozga sotmoqchiman</h2><p>Mahsulot → mijoz → to‘liq, qisman yoki nasiya.</p><small>Eski mijozni qidiring yoki yangi mijoz qo‘shing. Qarz mijozning umumiy hisobiga yoziladi.</small><b>Mijozga sotuv →</b></a>
        <a class="guide-tile" href="{{ route('inventory.index') }}"><span>📦</span><h2>Omborda nima bor?</h2><p>Mahsulotni qidiring, hajmni tanlang va qoldiqni ko‘ring.</p><small>Omborda bor dona bilan qurilmaga ajratilgan dona alohida. Qiymatni hisoblash — taxminiy baholash; bu hali ishlab topilgan foyda emas.</small><b>Omborni ochish →</b></a>
        <a class="guide-tile" href="{{ route('debts.index') }}"><span>🤝</span><h2>Qarzni olmoqchiman yoki to‘lamoqchiman</h2><p>Mijozlar bizga qarzdor. Biz yetkazuvchilarga qarzdor bo‘lishimiz mumkin.</p><small>Mijozdan to‘lov — kassaga pul qo‘shadi va qarzni kamaytiradi. Yetkazuvchiga to‘lov — kassadan pul ayiradi va qarzimizni kamaytiradi.</small><b>Qarzlar va to‘lovlar →</b></a>
        @can('view_cash')<a class="guide-tile" href="{{ route('cash.index') }}"><span>💵</span><h2>Pulni boshqarmoqchiman</h2><p>Kassaga pul qo‘shish, xarajat yozish va qolgan pulni ko‘rish.</p><small>Ijara, transport — xarajat. Egadan olingan yoki egaga berilgan pul alohida.</small><b>Kassani ochish →</b></a>@endcan
        <a class="guide-tile" href="{{ route('sales.history') }}"><span>🕒</span><h2>Oldingi sotuvni topmoqchiman</h2><p>Sana, mijoz yoki chek bo‘yicha qidiring.</p><small>Kim nima olgani, qancha to‘langani va sotuv vaqti saqlanadi. Kamera bilan tekshirish uchun sana va vaqtni ko‘ring.</small><b>Savdolar tarixi →</b></a>
        @can('view_reports')<a class="guide-tile" href="{{ route('reports.index') }}"><span>📈</span><h2>Natijalarni ko‘rmoqchiman</h2><p>Bugun, hafta, oy yoki o‘zingiz tanlagan davr.</p><small>Savdo summasi, kassaga tushgan pul va foyda turli ko‘rsatkichlar. Hisobotlarda har biri alohida hisoblanadi.</small><b>Hisobotlarni ochish →</b></a>@endcan
        @if(auth()->user()?->hasRole(['OWNER', 'ADMIN']))<a class="guide-tile" href="{{ route('admin.index') }}"><span>⚙</span><h2>Do‘konni sozlamoqchiman</h2><p>Do‘kon ma’lumotlari, xodimlar va telefonlar.</p><small>Eski qoldiq va qarzlarni «Boshlang‘ich qoldiqlar»dan kiriting. Xodimga faqat kerakli ruxsatlarni bering.</small><b>Sozlamalarni ochish →</b></a>@endif
    </div>
    <section class="guide-flow"><h2>Ma’lumotlarni qayerda o‘zgartiraman?</h2><div class="guide-directory-links">@can('manage_prices')<a class="trade-button trade-button-secondary" href="{{ route('catalog.index') }}">Mahsulotlar va doimiy narxlar →</a>@endcan @if(auth()->user()?->hasRole(['OWNER', 'ADMIN']))<a class="trade-button trade-button-secondary" href="{{ route('customers.index') }}">Mijozlar ro‘yxati →</a><a class="trade-button trade-button-secondary" href="{{ route('suppliers.index') }}">Yetkazuvchilar ro‘yxati →</a>@endif</div></section>
    <section class="guide-flow"><h2>Har amal tugagach nima o‘zgaradi?</h2><div><span>Mahsulot kirimi</span><b>→</b><span>Ombordagi dona oshadi</span><b>→</b><span>To‘lov bo‘lsa pul kamayadi, qolganiga qarz yoziladi</span></div><div><span>Sotuv</span><b>→</b><span>Ombordagi dona kamayadi</span><b>→</b><span>To‘lov kassaga tushadi, qolganiga mijoz qarzi yoziladi</span></div><div><span>Xarajat</span><b>→</b><span>Kassadagi pul kamayadi</span><b>→</b><span>Dashboard va hisobotda xarajat ko‘rinadi</span></div></section>
    <section class="guide-flow"><h2>Internet uzilsa</h2><p>Oddiy panel internet bilan ishlaydi. Internet yo‘q paytda oldindan ulangan qurilmadagi «Tezkor sotuv» oynasidan foydalaning. Qurilmaga ajratilgan mahsulotlar sotiladi. Internet qaytgach yozuvlar serverga yuboriladi; tekshirish talab qilgan yozuvlar sozlamalarda ko‘rinadi.</p><a class="trade-button trade-button-secondary" href="{{ route('pos.pwa') }}">Internetsiz ishlaydigan sotuv oynasi →</a><p class="workspace-caption">Birinchi ulash va ma’lumotlarni yuklash uchun internet kerak. Qurilmada saqlangan savdo serverga tasdiqlanmaguncha asosiy dashboardga qo‘shilmaydi.</p></section>
</x-layouts.app>
